linux:
  name: "Linux"
  agent:
    type: Unity::VM
    image: build-system/unity-ubuntu-18.04:v2.1411732
    flavor: b1.medium
  commands:
    - ./autogen.sh
    - make
    - make check 
    - mkdir -p build
    - cp ./yasm ./build/
    - cp COPYING ./build/LICENSE
    - cp BSD.txt ./build/
    # bitvect is under the Artistic license, not BSD
    - cp Artistic.txt ./build/
    - cp libyasm/bitvect.c ./build/
    - cp libyasm/bitvect.h ./build/
    - |
      set -euo pipefail
      wget https://public-stevedore.unity3d.com/r/public/7zip-linux-x64/24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip
      actual_hash=$(shasum -a 256 24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip | cut -f1 -d' ')
      if [ "$actual_hash" != c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b ] ; then
        echo "Error: 7zip-linux-x64 package hash does not match"
        exit 1
      fi
      unzip 24.07_9eb0ed9_c8efe29fa677babdb081ddd890b23883a08327cc3bd391a865cb165b2b08597b.zip
      cd build
      ../7za a yasm-linux-x64.7z *
  artifacts:
    build:
      paths:
        - build/yasm-linux-x64.7z
    test-results:
      paths:
        - test-suite.log

macos-x64:
  name: "macOS (x64)"
  agent:
    type: Unity::VM::osx
    image: build-system/unity-macos-10.15:v2.2005664
    flavor: b1.small
  commands:
    - |
      set -euo pipefail
      brew install automake autoconf
    - |
      set -euo pipefail
      ./autogen.sh
      make
      make check 
      mkdir -p build
      cp ./yasm ./build/
      cp COPYING ./build/LICENSE
      cp BSD.txt ./build/
      # bitvect is under the Artistic license, not BSD
      cp Artistic.txt ./build/
      cp libyasm/bitvect.c ./build/
      cp libyasm/bitvect.h ./build/
      wget https://public-stevedore.unity3d.com/r/public/7zip-mac-x64/24.07_9eb0ed9_7e1c33c7bc97514e2ab38ec6bd304e6986cd792c33356498057d9e54bc1f1d2d.zip
      actual_hash=$(shasum -a 256 24.07_9eb0ed9_7e1c33c7bc97514e2ab38ec6bd304e6986cd792c33356498057d9e54bc1f1d2d.zip | cut -f1 -d' ')
      if [ "$actual_hash" != 7e1c33c7bc97514e2ab38ec6bd304e6986cd792c33356498057d9e54bc1f1d2d ] ; then
        echo "Error: 7za package hash does not match"
        exit 1
      fi
      unzip 24.07_9eb0ed9_7e1c33c7bc97514e2ab38ec6bd304e6986cd792c33356498057d9e54bc1f1d2d.zip 7za
      cd build && ../7za a yasm-mac-x64.7z *
  artifacts:
    build:
      paths:
        - build/yasm-mac-x64.7z
    test-results:
      paths:
        - test-suite.log

macos-arm64:
  name: "macOS (arm64)"
  agent:
    type: Unity::VM::osx
    image: slough-ops/macos-13-arm64-xcode:v0.0.8-1332462
    model: M1
    flavor: m1.mac
  commands:
    - |
      set -euo pipefail
      brew install automake autoconf
    - |
      set -euo pipefail
      ./autogen.sh
      make
      make check 
      mkdir -p build
      cp ./yasm ./build/
      cp COPYING ./build/LICENSE
      cp BSD.txt ./build/
      # bitvect is under the Artistic license, not BSD
      cp Artistic.txt ./build/
      cp libyasm/bitvect.c ./build/
      cp libyasm/bitvect.h ./build/
      wget https://public-stevedore.unity3d.com/r/public/7zip-mac-arm64/24.07_9eb0ed9_27611f9240ca3b9087e240200711c3fd1ed4bbb964d6c1ad451f4e29a7c793ed.zip
      actual_hash=$(shasum -a 256 24.07_9eb0ed9_27611f9240ca3b9087e240200711c3fd1ed4bbb964d6c1ad451f4e29a7c793ed.zip | cut -f1 -d' ')
      if [ "$actual_hash" != 27611f9240ca3b9087e240200711c3fd1ed4bbb964d6c1ad451f4e29a7c793ed ] ; then
        echo "Error: 7za package hash does not match"
        exit 1
      fi
      unzip 24.07_9eb0ed9_27611f9240ca3b9087e240200711c3fd1ed4bbb964d6c1ad451f4e29a7c793ed.zip 7za
      chmod +x 7za
      cd build && ../7za a yasm-mac-arm64.7z *
  artifacts:
    build:
      paths:
        - build/yasm-mac-arm64.7z
    test-results:
      paths:
        - test-suite.log


windows:
  name: "Windows (x64)"
  agent:
    type: Unity::VM
    image: build-system/unity-extra-windows-10:v0.6-921129
    flavor: b1.medium
  commands:
    - cmake -S . -DBUILD_SHARED_LIBS=OFF -DCMAKE_GENERATOR_PLATFORM=x64
    - YASM-VERSION-GEN.bat
    - |
      "%ProgramFiles(x86)%\MSBuild\14.0\bin\msbuild.exe" yasm.sln /p:Configuration=Release /t:yasm
    - mkdir -p build
    - cp Release\yasm.exe build
    - cp COPYING build\LICENSE
    - cp BSD.txt build
    # bitvect is under the Artistic license, not BSD
    - cp Artistic.txt build
    - cp libyasm/bitvect.c build
    - cp libyasm/bitvect.h build
    - cd build && 7z a yasm-win-x64.7z *
  artifacts:
    build:
      paths:
        - build/yasm-win-x64.7z
    test-results:
      paths:
        - test-suite.log
        
deploy-test:
  name: "Deploy to Stevedore (Test repository)"
  agent:
    type: Unity::VM
    image: build-system/unity-extra-ubuntu-18.04:latest
    flavor: b1.small
  dependencies:
    - .yamato/build.yml#linux
    - .yamato/build.yml#macos-x64
    - .yamato/build.yml#macos-arm64
    - .yamato/build.yml#windows
  commands:
    - curl -sSo StevedoreUpload.exe "$STEVEDORE_UPLOAD_TOOL_URL"
    - mono StevedoreUpload.exe --append-manifest=- --version-len=12 --repo=testing --version="$GIT_REVISION" build/*
  triggers:
    branches:
      only:
      - "/.*/"
      except:
      - "master"
      
deploy-public:
  name: "Deploy to Stevedore (Public repository)"
  agent:
    type: Unity::VM
    image: build-system/unity-extra-ubuntu-18.04:latest
    flavor: b1.small
  dependencies:
    - .yamato/build.yml#linux
    - .yamato/build.yml#macos-x64
    - .yamato/build.yml#macos-arm64
    - .yamato/build.yml#windows
  commands:
    - curl -sSo StevedoreUpload.exe "$STEVEDORE_UPLOAD_TOOL_URL"
    - mono StevedoreUpload.exe --append-manifest=- --version-len=12 --repo=public --version="$GIT_REVISION" build/*
